#!/usr/local/bin/python
# IMPORTANT THE ABOVE SHOULD MATCH THE PATH TO PYTHON ON YOUR MACHINE

import faceDetection as tTest
import sys
import os
import crop
import cv2
from face_rec.recognize import EigenfaceRecon,FishRecon,EigenRecon
from face_rec.utils import make_array,judge
from PIL import Image
import matplotlib.pyplot as plt

import numpy as np


filepath = sys.argv[1]

rect = tTest.getRectangle(filepath)

contents = open('avgHW.csv','r').read()

H,W = contents.split(',')
H = int(H)
W = int(W)
centerY = (rect[3] + rect[1])/2
centerX = (rect[2] + rect[0])/2

# im = crop.cropp(filepath,rect)
# contents = open('avgHW.csv','r').read()

# H,W = contents.split(',')
# H = int(H)
# W = int(W)
# centerY = (rect[3] + rect[1])/2
# centerX = (rect[2] + rect[0])/2

im = crop.cropp(filepath,rect)

arr = np.asarray(im)
plt.imshow(arr)
plt.show()

# recon = EigenRecon('bin/phase2_dataset_1/')
recon = FishRecon('bin/phase2_fish_1/')

best_idx,max_match = recon.recognize(arr.flatten())
print best_idx
print max_match
